export type Product = {
  id: string;
  name: string;
  sku: string;
  batchNumber: string;
  category: string;
  status: "In Stock" | "Low Stock" | "Out of Stock";
};

export const products: Product[] = [
  {
    id: "PROD-001",
    name: "Laptop Dell XPS 15",
    sku: "DELL-XPS15-001",
    batchNumber: "BATCH-001",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-002",
    name: "iPhone 15 Pro",
    sku: "APPLE-IP15P-002",
    batchNumber: "BATCH-002",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-003",
    name: 'Samsung TV 55"',
    sku: "SAMSUNG-TV55-003",
    batchNumber: "BATCH-003",
    category: "Electronics",
    status: "Low Stock",
  },
  {
    id: "PROD-004",
    name: "Sony Headphones WH-1000XM5",
    sku: "SONY-WH1000XM5-004",
    batchNumber: "BATCH-004",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-005",
    name: 'iPad Pro 12.9"',
    sku: "APPLE-IPADPRO-005",
    batchNumber: "BATCH-005",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-006",
    name: "Office Desk Chair",
    sku: "FURN-CHAIR-006",
    batchNumber: "BATCH-006",
    category: "Furniture",
    status: "Low Stock",
  },
  {
    id: "PROD-007",
    name: "Wooden Dining Table",
    sku: "FURN-TABLE-007",
    batchNumber: "BATCH-007",
    category: "Furniture",
    status: "Low Stock",
  },
  {
    id: "PROD-008",
    name: "Cotton T-Shirt (L)",
    sku: "CLOTH-TSHIRT-008",
    batchNumber: "BATCH-008",
    category: "Clothing",
    status: "In Stock",
  },
  {
    id: "PROD-009",
    name: "Denim Jeans (32)",
    sku: "CLOTH-JEANS-009",
    batchNumber: "BATCH-009",
    category: "Clothing",
    status: "In Stock",
  },
  {
    id: "PROD-010",
    name: "PS5",
    sku: "SONY-PS5-010",
    batchNumber: "BATCH-010",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-011",
    name: "MacBook Pro 16",
    sku: "APPLE-MBP16-011",
    batchNumber: "BATCH-011",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-012",
    name: "Wireless Mouse",
    sku: "LOGITECH-MOUSE-012",
    batchNumber: "BATCH-012",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-013",
    name: "Mechanical Keyboard",
    sku: "KEYCHRON-KB-013",
    batchNumber: "BATCH-013",
    category: "Electronics",
    status: "Low Stock",
  },
  {
    id: "PROD-014",
    name: "4K Monitor 27\"",
    sku: "LG-MONITOR-014",
    batchNumber: "BATCH-014",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-015",
    name: "Bluetooth Speaker",
    sku: "JBL-SPEAKER-015",
    batchNumber: "BATCH-015",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-016",
    name: "Gaming Chair",
    sku: "RAZER-CHAIR-016",
    batchNumber: "BATCH-016",
    category: "Furniture",
    status: "Low Stock",
  },
  {
    id: "PROD-017",
    name: "Leather Sofa",
    sku: "FURN-SOFA-017",
    batchNumber: "BATCH-017",
    category: "Furniture",
    status: "In Stock",
  },
  {
    id: "PROD-018",
    name: "Coffee Table",
    sku: "FURN-TABLE-018",
    batchNumber: "BATCH-018",
    category: "Furniture",
    status: "In Stock",
  },
  {
    id: "PROD-019",
    name: "Bookshelf",
    sku: "FURN-SHELF-019",
    batchNumber: "BATCH-019",
    category: "Furniture",
    status: "Low Stock",
  },
  {
    id: "PROD-020",
    name: "Hoodie (M)",
    sku: "CLOTH-HOODIE-020",
    batchNumber: "BATCH-020",
    category: "Clothing",
    status: "In Stock",
  },
  {
    id: "PROD-021",
    name: "Running Shoes",
    sku: "NIKE-SHOES-021",
    batchNumber: "BATCH-021",
    category: "Clothing",
    status: "In Stock",
  },
  {
    id: "PROD-022",
    name: "Winter Jacket",
    sku: "COLUMBIA-JACKET-022",
    batchNumber: "BATCH-022",
    category: "Clothing",
    status: "Low Stock",
  },
  {
    id: "PROD-023",
    name: "Smartwatch",
    sku: "APPLE-WATCH-023",
    batchNumber: "BATCH-023",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-024",
    name: "Noise-Cancelling Headphones",
    sku: "BOSE-HEADPHONES-024",
    batchNumber: "BATCH-024",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-025",
    name: "External SSD 1TB",
    sku: "SAMSUNG-SSD-025",
    batchNumber: "BATCH-025",
    category: "Electronics",
    status: "Low Stock",
  },
  {
    id: "PROD-026",
    name: "Gaming Laptop",
    sku: "ASUS-LAPTOP-026",
    batchNumber: "BATCH-026",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-027",
    name: "Wireless Earbuds",
    sku: "SONY-EARBUDS-027",
    batchNumber: "BATCH-027",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-028",
    name: "Desk Lamp",
    sku: "IKEA-LAMP-028",
    batchNumber: "BATCH-028",
    category: "Furniture",
    status: "In Stock",
  },
  {
    id: "PROD-029",
    name: "Office Desk",
    sku: "FURN-DESK-029",
    batchNumber: "BATCH-029",
    category: "Furniture",
    status: "Low Stock",
  },
  {
    id: "PROD-030",
    name: "Bean Bag Chair",
    sku: "FURN-BEANBAG-030",
    batchNumber: "BATCH-030",
    category: "Furniture",
    status: "In Stock",
  },
  {
    id: "PROD-031",
    name: "Formal Shirt (L)",
    sku: "CLOTH-SHIRT-031",
    batchNumber: "BATCH-031",
    category: "Clothing",
    status: "In Stock",
  },
  {
    id: "PROD-032",
    name: "Sneakers",
    sku: "ADIDAS-SHOES-032",
    batchNumber: "BATCH-032",
    category: "Clothing",
    status: "In Stock",
  },
  {
    id: "PROD-033",
    name: "Backpack",
    sku: "NIKE-BACKPACK-033",
    batchNumber: "BATCH-033",
    category: "Clothing",
    status: "Low Stock",
  },
  {
    id: "PROD-034",
    name: "Smart Thermostat",
    sku: "NEST-THERMOSTAT-034",
    batchNumber: "BATCH-034",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-035",
    name: "Robot Vacuum",
    sku: "ROOMBA-VACUUM-035",
    batchNumber: "BATCH-035",
    category: "Electronics",
    status: "In Stock",
  },
  {
    id: "PROD-036",
    name: "Air Purifier",
    sku: "DYSON-PURIFIER-036",
    batchNumber: "BATCH-036",
    category: "Electronics",
    status: "Low Stock",
  },
  {
    id: "PROD-037",
    name: "Electric Kettle",
    sku: "KITCHEN-KETTLE-037",
    batchNumber: "BATCH-037",
    category: "Home Appliances",
    status: "In Stock",
  },
  {
    id: "PROD-038",
    name: "Blender",
    sku: "KITCHEN-BLENDER-038",
    batchNumber: "BATCH-038",
    category: "Home Appliances",
    status: "In Stock",
  },
  {
    id: "PROD-039",
    name: "Toaster",
    sku: "KITCHEN-TOASTER-039",
    batchNumber: "BATCH-039",
    category: "Home Appliances",
    status: "Low Stock",
  },
  {
    id: "PROD-040",
    name: "Microwave Oven",
    sku: "KITCHEN-MICROWAVE-040",
    batchNumber: "BATCH-040",
    category: "Home Appliances",
    status: "In Stock",
  },
  {
    id: "PROD-041",
    name: "Rice Cooker",
    sku: "KITCHEN-RICECOOKER-041",
    batchNumber: "BATCH-041",
    category: "Home Appliances",
    status: "In Stock",
  },
  {
    id: "PROD-042",
    name: "Electric Grill",
    sku: "KITCHEN-GRILL-042",
    batchNumber: "BATCH-042",
    category: "Home Appliances",
    status: "Low Stock",
  },
  {
    id: "PROD-043",
    name: "Stand Mixer",
    sku: "KITCHEN-MIXER-043",
    batchNumber: "BATCH-043",
    category: "Home Appliances",
    status: "In Stock",
  },
  {
    id: "PROD-044",
    name: "Food Processor",
    sku: "KITCHEN-PROCESSOR-044",
    batchNumber: "BATCH-044",
    category: "Home Appliances",
    status: "In Stock",
  },
  {
    id: "PROD-045",
    name: "Coffee Maker",
    sku: "KITCHEN-COFFEE-045",
    batchNumber: "BATCH-045",
    category: "Home Appliances",
    status: "Low Stock",
  },
  {
    id: "PROD-046",
    name: "Air Fryer",
    sku: "KITCHEN-AIRFRYER-046",
    batchNumber: "BATCH-046",
    category: "Home Appliances",
    status: "In Stock",
  },
  {
    id: "PROD-047",
    name: "Slow Cooker",
    sku: "KITCHEN-SLOWCOOKER-047",
    batchNumber: "BATCH-047",
    category: "Home Appliances",
    status: "In Stock",
  },
  {
    id: "PROD-048",
    name: "Electric Pressure Cooker",
    sku: "KITCHEN-PRESSURECOOKER-048",
    batchNumber: "BATCH-048",
    category: "Home Appliances",
    status: "Low Stock",
  },
  {
    id: "PROD-049",
    name: "Hand Mixer",
    sku: "KITCHEN-HANDMIXER-049",
    batchNumber: "BATCH-049",
    category: "Home Appliances",
    status: "In Stock",
  },
  {
    id: "PROD-050",
    name: "Juicer",
    sku: "KITCHEN-JUICER-050",
    batchNumber: "BATCH-050",
    category: "Home Appliances",
    status: "In Stock",
  },
];